# .bashrc for System Alliance
#
# There are 3 different types of shells in bash: the login shell, normal shell
# and interactive shell. Login shells read ~/.profile and interactive shells
# read ~/.bashrc; in our setup, /etc/profile sources ~/.bashrc - thus all
# settings made here will also take effect in a login shell.
#
# NOTE: It is recommended to make language settings in ~/.profile rather than
# here, since multilingual X sessions would not work properly if LANG is over-
# ridden in every subshell.

# If not running interactively, don't do anything
#
[ -z "$PS1" ] && return

# Don't put duplicate lines in the history.
#
HISTCONTROL=ignoredups:ignorespace

# Append to the history file, do not overwrote it.
#
shopt -s histappend

# Some application read the EDITOR variable to determine your favorite
# text editor.
#
export EDITOR=/usr/bin/vim

# User path.
#
export PATH=$PATH:${HOME}/.local/bin
